server:
  port: 8080
spring:
  jpa:
    hibernate:
      ddl-auto: validate
      show-sql: true
      format_sql: true
      database-platform: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:mysql://localhost:3306/db_joyeria_marli?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
flyway:
  enabled: true
  locations: classpath:/db/migration
  baseline-on-migrate: true
  baseline-version: 0
